import = ["/Users/hao/.config/alacritty/colors/carbonfox.toml"]

[shell]
# program = "/opt/homebrew/bin/fish"
program = "/opt/homebrew/bin/nu"

# [env]
# SHELL_OPTS = "-c 'globsstar'"

[font]
size = 10.2

[font.bold]
family = "BlexMono Nerd Font"
style = "Semibold"

[font.italic]
family = "BlexMono Nerd Font"
style = "Italic"

[font.normal]
family = "BlexMono Nerd Font"
style = "Medium"

[font.offset]
x = 1
y = 15

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Super"

[[keyboard.bindings]]
chars = "\u0001"
key = "A"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0003"
key = "C"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0004"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0005"
key = "E"
mods = "Command"

[[keyboard.bindings]]
chars = """

"""
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u000B"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u000E"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u000F"
key = "O"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0010"
key = "P"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0012"
key = "R"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "U"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0017"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command|Shift"

[scrolling]
history = 10000

# [selection]
# save_to_clipboard = true

[window]
decorations = "buttonless"
opacity = 0.87
startup_mode = "Maximized"

[window.padding]
x = 15
y = 20

[window.position]
x = 0
y = 0
