
[terminal.shell]
# program = "/opt/homebrew/bin/fish"
program = "/opt/homebrew/bin/nu"

# [env]
# SHELL_OPTS = "-c 'globsstar'"

[font]
size = 10.2

[font.bold]
family = "BlexMono Nerd Font"
style = "Semibold"

[font.italic]
family = "BlexMono Nerd Font"
style = "Italic"

[font.normal]
family = "BlexMono Nerd Font"
style = "Medium"

[font.offset]
x = 1
y = 14

[font.glyph_offset]
y = 7

[scrolling]
history = 10000
multiplier = 20

# [selection]
# save_to_clipboard = true

[window]
decorations = "buttonless"
opacity = 0.84
startup_mode = "Maximized"
blur = true
option_as_alt = "Both"

[window.padding]
x = 15
y = 20

[window.position]
x = 0
y = 0

[general]
import = ["/Users/hao/.config/alacritty/colors/carbonfox.toml", "/Users/hao/.config/alacritty/key_bindings.toml"]

[terminal]
